//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class HumanMoving
{
	public String humanId;
	public Lumen.Vector3 position;
	public Lumen.Rotation3 rotation;
    public int imageU;
    public int imageV;
    public int imageVH;
}

