//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Lumen {
	public class Rotation3
	{
		public double? pitchCcwDeg;
		public double? yawCcwDeg;
		public double? rollCcwDeg;

		public Rotation3 ()
		{
		}
	}
}